name: Update Leaderboard

on:
  schedule:
    # 0 8 * * 1,4 = lundi et jeudi à 8h00 UTC 
    - cron: '0 8 * * 1,4'
  workflow_dispatch: 

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update script
        run: python update_leaderboard.py

      - name: Commit and push if leaderboard changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add leaderboard.json leaderboard_prev.json
          git commit -m "Update leaderboard [bot]" || echo "No changes to commit"
          git push
